language: go
go: 1.9
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/fd/go-shellwords/shellwords
  - go get gopkg.in/fsnotify/fsnotify.v1
  - go get github.com/runner-mei/cron
  - go get github.com/lib/pq
  - go get golang.org/x/text
  - go get github.com/kardianos/osext
  - go get github.com/hjson/hjson-go
  
services:
  - postgres 

before_script:
  - psql -c "CREATE USER tpt WITH PASSWORD 'extreme';" -U postgres
  - psql -c "create database tpt_models_test with OWNER = tpt;" -U postgres
script:
  - go test -v
