language: go
go: "1.10"
install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/fd/go-shellwords/shellwords
  - go get gopkg.in/fsnotify/fsnotify.v1
  - go get github.com/runner-mei/cron
  - go get github.com/lib/pq
  - go get golang.org/x/text
  - go get github.com/kardianos/osext
  - go get github.com/hjson/hjson-go
  
services:
  - postgres 

addons:
  postgresql: "9.6"

before_script:
  - psql -c "CREATE USER schdtest WITH PASSWORD '123456';" -U postgres
  - psql -c "create database schd_test with OWNER = schdtest;" -U postgres
script:
  - go test -v
